### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ank-tw** [avaidyam/CGSKeyboardShortcut#1]
Hi, I would like to use this on a potentially MIT-licensed open source project I'm putting together - was wondering what the license of this code is. Thanks!

**Comment by ank-tw** [comment]
I have updated it to work cleanly in the latest Xcode - would be very happy to contribute a PR but want to ensure first that the license is compatible with what I need to do. @avaidyam

**Comment by avaidyam** [comment]
Please consider this repo MIT licensed - and if you would like, you may add the `LICENSE.md` file in your PR. Thanks!

**Comment by ank-tw** [comment]
Excellent! I have opened a [PR](https://github.com/avaidyam/CGSKeyboardShortcut/pull/2), let me know what you think - I have included a sample project, too.

**Comment by avaidyam** [comment]
It looked good to me! Thanks!
